security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # Ou 'username' si tu utilises un autre identifiant

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
            remember_me:
                secret: '%kernel.secret%'

    access_control:
        # Allow access to /login without being authenticated
        - { path: ^/login, allow_if: "1" }
        
        # Allow users who are admins to access the /admin path
        - { path: ^/admin, allow_if: "user and user.isAdmin() == true" }
        
        # Allow users who are not locked to access other pages
        - { path: ^/.*, allow_if: "user and user.isLocked() != true" }
        
        # Allow all authenticated users to access other routes (outside /admin or /login)
        - { path: ^/, allow_if: "user" }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
