version: "3.8"
services:

    db:
        image: mysql:8.1.0  
        container_name: db_docker_symfony
        restart: always
        volumes:
          - ./server/mysql_data:/var/lib/mysql    #this line maps the content of ./server/mysql_data in your pc to the /var/lib/mysql of the container
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_USER: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: maildev_docker_symfony
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "8081:80"
        restart: always
        networks:
            - dev

    www:
        build: php
        container_name: www_docker_symfony
        ports:
          - "8000:8000"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ../:/var/www
        restart: always
        networks:
            - dev

networks:
    dev:
