<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerImxTGFJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerImxTGFJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerImxTGFJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerImxTGFJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerImxTGFJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'ImxTGFJ',
    'container.build_id' => 'a43ac3fb',
    'container.build_time' => 1742394622,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerImxTGFJ');
