<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN1Hx6Wj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN1Hx6Wj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN1Hx6Wj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN1Hx6Wj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN1Hx6Wj\App_KernelDevDebugContainer([
    'container.build_hash' => 'N1Hx6Wj',
    'container.build_id' => '795273b7',
    'container.build_time' => 1742392727,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN1Hx6Wj');
