<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3qkZUff\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3qkZUff/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3qkZUff.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3qkZUff\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3qkZUff\App_KernelDevDebugContainer([
    'container.build_hash' => '3qkZUff',
    'container.build_id' => '921177f5',
    'container.build_time' => 1742394222,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3qkZUff');
